# url: http://host.docker.internal:9009/api/prom/push
url: http://localhost:9009/api/prom/push
remote_timeout: 30s
push_interval: 2s
name: Test
histogram_boundaries:
  - -25
  - 0
  - 25
quantiles:
  - 0.25
  - 0.5
  - 0.75
headers:
  X-Scope-OrgID: 5